# Generated by Django 6.0.3 on 2026-03-15 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='วันที่เพิ่มข้อมูล'),
        ),
    ]
